---
apiVersion: v1
kind: Service
metadata:
  name: shopfront2
  labels:
    app: shopfront2
spec:
  type: NodePort
  selector:
    app: shopfront2
  ports:
  - protocol: TCP
    port: 8010
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopfront2
spec:
  selector:
    matchLabels:
      app: shopfront2
  replicas: 1
  template:
    metadata:
      labels:
        app: shopfront2
    spec:
      containers:
      - name: shopfront2
        image: phaneendrat7/shopfront:1.0.0
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1
